### ISSUE TITLE
Add gh-pages (hosted) version.

### ISSUE THREAD

**Issue by kalisjoshua** [Mike-Risher/5e-DnD-Character-Generator#2]
You should publish this to GitHub pages so that it is easily available to view.

**Comment by Mike-Risher** [comment]
I'm new to GitHub and don't fully understand how it works.  Could you let
me know how to do what you're asking?  Thanks in advance.

**Comment by kalisjoshua** [comment]
The easy way to do it would be to simply add a new branch - from the current master - and GitHub should pick that up after a few moments and begin serving at http://Mike-Risher.github.io/5e-DnD-Character-Generator; I think.

**Comment by Mike-Risher** [comment]
Sorry for the long delay.  This has been done.  See this URL:  http://mike-risher.github.io/5e-DnD-Character-Generator/
