### ISSUE TITLE
Would you consider updating for races / spells in Elemental Evil?

### ISSUE THREAD

**Issue by thejoester** [Mike-Risher/5e-DnD-Character-Generator#3]
Would you consider updating for races / spells in Elemental Evil?

details can be found in the WOTC free PDF: http://media.wizards.com/2015/downloads/dnd/EE_PlayersCompanion.pdf

**Comment by Mike-Risher** [comment]
Will do, but need some time. I'll try to get to it within a month, and hopefully within 2 weeks.

**Comment by Mike-Risher** [comment]
Done
